
select * from customer limit 20

--1. Total Revenue generated by male/female customer?

SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--2. Which customer used a discount but still spent more than the  average purchase amount?
 SELECT "Customer ID", "Purchase Amount (USD)"
 FROM customer
 WHERE "Discount Applied"= 'Yes' AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customer)

 --3. Which are the top 5 products with the highest average review rating?
 SELECT "Item Purchased", ROUND(AVG("Review Rating":: Numeric),2) AS "AVERAGE PRODUCT RATING"
 FROM customer
 GROUP BY "Item Purchased"
 ORDER BY AVG("Review Rating") DESC
 LIMIT 5;

--4. Compare the Average Purchase Amount between Standard and express Shipping.
SELECT "Shipping Type", 
ROUND(AVG("Purchase Amount (USD)"),2) 
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type"


--5. Do Subscribed Customer spend more? Compare Average spend and total revenue between subscribers and non-subscribers.
SELECT "Subscription Status",
COUNT("Customer ID") AS total_customers,
ROUND(AVG("Purchase Amount (USD)"::numeric), 2) AS avg_spend,
ROUND(SUM("Purchase Amount (USD)"::numeric), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status";

--6. Which 5 products have highest percentage of Purchases with discounts applied? 
SELECT "Item Purchased",
ROUND((SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*)) * 100, 2) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;


--7. Segment Customer into New, returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
COUNT("Customer ID") AS total_customers
FROM customer
GROUP BY customer_segment
ORDER BY total_customers DESC;


--8. What are the top 3 most purchased products within each category?
SELECT *
FROM (
    SELECT "Category", "Item Purchased",
    COUNT(*) AS purchase_count, ROW_NUMBER() OVER (PARTITION BY "Category"ORDER BY COUNT(*) DESC) AS "Item Rank" FROM customer
    GROUP BY "Category", "Item Purchased") ranked_products WHERE "Item Rank" <= 3;


--9. Are the customers who are repaeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT "Subscription Status",
COUNT("Customer ID") AS repeat_buyer
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";


--10. What is the revenue contribution of each age group?
SELECT "Age group",
SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age group"
ORDER BY total_revenue DESC;

















